#include "format_info.h"

namespace loon::gpu {
static constexpr FormatInfo kFormatInfo[] = {
    {.format = Format::R8Unorm, .block_size_bytes = 1},
    {.format = Format::R8Snorm, .block_size_bytes = 1},
    {.format = Format::R8Uint, .block_size_bytes = 1},
    {.format = Format::R8Sint, .block_size_bytes = 1},
    {.format = Format::R16Unorm, .block_size_bytes = 2},
    {.format = Format::R16Snorm, .block_size_bytes = 2},
    {.format = Format::R16Uint, .block_size_bytes = 2},
    {.format = Format::R16Sint, .block_size_bytes = 2},
    {.format = Format::R16Float, .block_size_bytes = 2},
    {.format = Format::RG8Unorm, .block_size_bytes = 2},
    {.format = Format::RG8Snorm, .block_size_bytes = 2},
    {.format = Format::RG8Uint, .block_size_bytes = 2},
    {.format = Format::RG8Sint, .block_size_bytes = 2},
    {.format = Format::R32Float, .block_size_bytes = 4},
    {.format = Format::R32Uint, .block_size_bytes = 4},
    {.format = Format::R32Sint, .block_size_bytes = 4},
    {.format = Format::RG16Unorm, .block_size_bytes = 4},
    {.format = Format::RG16Snorm, .block_size_bytes = 4},
    {.format = Format::RG16Uint, .block_size_bytes = 4},
    {.format = Format::RG16Sint, .block_size_bytes = 4},
    {.format = Format::RG16Float, .block_size_bytes = 4},
    {.format = Format::RGBA8Unorm, .block_size_bytes = 4},
    {.format = Format::RGBA8UnormSrgb, .block_size_bytes = 4},
    {.format = Format::RGBA8Snorm, .block_size_bytes = 4},
    {.format = Format::RGBA8Uint, .block_size_bytes = 4},
    {.format = Format::RGBA8Sint, .block_size_bytes = 4},
    {.format = Format::BGRA8Unorm, .block_size_bytes = 4},
    {.format = Format::BGRA8UnormSrgb, .block_size_bytes = 4},
    {.format = Format::RGB10A2Uint, .block_size_bytes = 4},
    {.format = Format::RGB10A2Unorm, .block_size_bytes = 4},
    {.format = Format::RG11B10Ufloat, .block_size_bytes = 4},
    {.format = Format::RGB9E5Ufloat, .block_size_bytes = 4},
    {.format = Format::RG32Float, .block_size_bytes = 8},
    {.format = Format::RG32Uint, .block_size_bytes = 8},
    {.format = Format::RG32Sint, .block_size_bytes = 8},
    {.format = Format::RGBA16Unorm, .block_size_bytes = 8},
    {.format = Format::RGBA16Snorm, .block_size_bytes = 8},
    {.format = Format::RGBA16Uint, .block_size_bytes = 8},
    {.format = Format::RGBA16Sint, .block_size_bytes = 8},
    {.format = Format::RGBA16Float, .block_size_bytes = 8},
    {.format = Format::RGBA32Float, .block_size_bytes = 16},
    {.format = Format::RGBA32Uint, .block_size_bytes = 16},
    {.format = Format::RGBA32Sint, .block_size_bytes = 16},
    {.format = Format::Stencil8, .block_size_bytes = 1},
    {.format = Format::Depth16Unorm, .block_size_bytes = 2},
    {.format = Format::Depth24Plus, .block_size_bytes = 4},
    {.format = Format::Depth24PlusStencil8, .block_size_bytes = 4},
    {.format = Format::Depth32Float, .block_size_bytes = 4},
    {.format = Format::Depth32FloatStencil8, .block_size_bytes = 5},
    {
        .format           = Format::BC1RGBAUnorm,
        .block_size_bytes = 8,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::BC1RGBAUnormSrgb,
        .block_size_bytes = 8,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::BC2RGBAUnorm,
        .block_size_bytes = 16,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::BC2RGBAUnormSrgb,
        .block_size_bytes = 16,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::BC3RGBAUnorm,
        .block_size_bytes = 16,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::BC3RGBAUnormSrgb,
        .block_size_bytes = 16,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::BC4RUnorm,
        .block_size_bytes = 8,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::BC4RSnorm,
        .block_size_bytes = 8,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::BC5RGUnorm,
        .block_size_bytes = 16,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::BC5RGSnorm,
        .block_size_bytes = 16,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::BC6HRGBUfloat,
        .block_size_bytes = 16,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::BC6HRGBFloat,
        .block_size_bytes = 16,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::BC7RGBAUnorm,
        .block_size_bytes = 16,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::BC7RGBAUnormSrgb,
        .block_size_bytes = 16,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::ETC2RGB8Unorm,
        .block_size_bytes = 8,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::ETC2RGB8UnormSrgb,
        .block_size_bytes = 8,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::ETC2RGB8A1Unorm,
        .block_size_bytes = 8,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::ETC2RGB8A1UnormSrgb,
        .block_size_bytes = 8,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::ETC2RGBA8Unorm,
        .block_size_bytes = 8,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::ETC2RGBA8UnormSrgb,
        .block_size_bytes = 16,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::EACR11Unorm,
        .block_size_bytes = 8,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::EACR11Snorm,
        .block_size_bytes = 8,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::EACRG11Unorm,
        .block_size_bytes = 16,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::EACRG11Snorm,
        .block_size_bytes = 16,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::ASTC4x4Unorm,
        .block_size_bytes = 16,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::ASTC4x4UnormSrgb,
        .block_size_bytes = 16,
        .block_width      = 4,
        .block_height     = 4,
    },
    {
        .format           = Format::ASTC5x4Unorm,
        .block_size_bytes = 16,
        .block_width      = 5,
        .block_height     = 4,
    },
    {
        .format           = Format::ASTC5x4UnormSrgb,
        .block_size_bytes = 16,
        .block_width      = 5,
        .block_height     = 4,
    },
    {
        .format           = Format::ASTC5x5Unorm,
        .block_size_bytes = 16,
        .block_width      = 5,
        .block_height     = 5,
    },
    {
        .format           = Format::ASTC5x5UnormSrgb,
        .block_size_bytes = 16,
        .block_width      = 5,
        .block_height     = 5,
    },
    {
        .format           = Format::ASTC6x5Unorm,
        .block_size_bytes = 16,
        .block_width      = 6,
        .block_height     = 5,
    },
    {
        .format           = Format::ASTC6x5UnormSrgb,
        .block_size_bytes = 16,
        .block_width      = 6,
        .block_height     = 5,
    },
    {
        .format           = Format::ASTC6x6Unorm,
        .block_size_bytes = 16,
        .block_width      = 6,
        .block_height     = 6,
    },
    {
        .format           = Format::ASTC6x6UnormSrgb,
        .block_size_bytes = 16,
        .block_width      = 6,
        .block_height     = 6,
    },
    {
        .format           = Format::ASTC8x5Unorm,
        .block_size_bytes = 16,
        .block_width      = 8,
        .block_height     = 5,
    },
    {
        .format           = Format::ASTC8x5UnormSrgb,
        .block_size_bytes = 16,
        .block_width      = 8,
        .block_height     = 5,
    },
    {
        .format           = Format::ASTC8x6Unorm,
        .block_size_bytes = 16,
        .block_width      = 8,
        .block_height     = 6,
    },
    {
        .format           = Format::ASTC8x6UnormSrgb,
        .block_size_bytes = 16,
        .block_width      = 8,
        .block_height     = 6,
    },
    {
        .format           = Format::ASTC8x8Unorm,
        .block_size_bytes = 16,
        .block_width      = 8,
        .block_height     = 8,
    },
    {
        .format           = Format::ASTC8x8UnormSrgb,
        .block_size_bytes = 16,
        .block_width      = 8,
        .block_height     = 8,
    },
    {
        .format           = Format::ASTC10x5Unorm,
        .block_size_bytes = 16,
        .block_width      = 10,
        .block_height     = 5,
    },
    {
        .format           = Format::ASTC10x5UnormSrgb,
        .block_size_bytes = 16,
        .block_width      = 10,
        .block_height     = 5,
    },
    {
        .format           = Format::ASTC10x6Unorm,
        .block_size_bytes = 16,
        .block_width      = 10,
        .block_height     = 6,
    },
    {
        .format           = Format::ASTC10x6UnormSrgb,
        .block_size_bytes = 16,
        .block_width      = 10,
        .block_height     = 6,
    },
    {
        .format           = Format::ASTC10x8Unorm,
        .block_size_bytes = 16,
        .block_width      = 10,
        .block_height     = 8,
    },
    {
        .format           = Format::ASTC10x8UnormSrgb,
        .block_size_bytes = 16,
        .block_width      = 10,
        .block_height     = 8,
    },
    {
        .format           = Format::ASTC10x10Unorm,
        .block_size_bytes = 16,
        .block_width      = 10,
        .block_height     = 10,
    },
    {
        .format           = Format::ASTC10x10UnormSrgb,
        .block_size_bytes = 16,
        .block_width      = 10,
        .block_height     = 10,
    },
    {
        .format           = Format::ASTC12x10Unorm,
        .block_size_bytes = 16,
        .block_width      = 12,
        .block_height     = 10,
    },
    {
        .format           = Format::ASTC12x10UnormSrgb,
        .block_size_bytes = 16,
        .block_width      = 12,
        .block_height     = 10,
    },
    {
        .format           = Format::ASTC12x12Unorm,
        .block_size_bytes = 16,
        .block_width      = 12,
        .block_height     = 12,
    },
    {
        .format           = Format::ASTC12x12UnormSrgb,
        .block_size_bytes = 16,
        .block_width      = 12,
        .block_height     = 12,
    },
};

static constexpr auto checkTable = []() {
    bool result = true;
    for (uint32_t i = 1; i < static_cast<uint32_t>(Format::ValidCount); ++i) {
        result &= (static_cast<uint32_t>(kFormatInfo[i - 1].format) == i);
    }
    return result;
};
static_assert(checkTable());

FormatInfo get_format_info(Format f) {
    return kFormatInfo[static_cast<uint32_t>(f) - 1];
}



}  // namespace loon::gpu